version: '3.9'

services:
  db:
    image: postgres:16
    container_name: app-db-dev
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: main_dev
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U app']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-dev-data:/var/lib/postgresql/data
    networks:
      - app

volumes:
  db-dev-data:

networks:
  app:
    driver: bridge
